name: Run Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start Docker containers
        run: docker-compose up -d --build

      - name: Wait for services
        run: |
          echo "Waiting 5 seconds for Redis"
          sleep 5

      - name: Install Composer dependencies inside container
        run: docker-compose exec app composer install --no-interaction --prefer-dist

      - name: Run PHPUnit tests inside container
        run: docker-compose exec app vendor/bin/phpunit

      - name: Tear down Docker containers
        run: docker-compose down